name: Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copy files to server
        run: |
          scp -r . ${{ secrets.USER }}@${{ secrets.HOST }}:/home/ubuntu/inves-master

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            cd /home/ubuntu/inves-master
            docker stop inves || true
            docker rm inves || true
            docker build -t inves-site .
            docker run -d --name inves -p 80:80 inves-site
          EOF
