name: Start Docker App on EC2

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # 9 AM UTC daily

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
    - name: Start Docker App
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          bash ~/start-app.sh
